### ISSUE TITLE
Jobs and players not counting

### ISSUE THREAD

**Issue by gingygames** [ESX-PUBLIC/esx_scoreboard#10]
After update of ESX, not reloading of player list was fixed, but players are still experiencing issue of NOT COUNTING PLAYRS ON JOB and not counting total players... in fact our players told me that scoreboard shows 1/32 and then suddenly 34/32 when there is about 18 players online...
ES5, latest ESX.

**Comment by gingygames** [comment]
server artifacts update solved it

**Comment by HawaiiBeach** [comment]
Uuum I dont think server artifacts are relevant. Make sure you use the latest ESX
