### ISSUE TITLE
Not getting roleplay names...

### ISSUE THREAD

**Issue by FSJerrA** [ESX-PUBLIC/esx_scoreboard#15]
At the moment it is impossible for me to get the Roleplay names. Tried everything. Ive seen other servers with jsfour-register instead of esx_identity and they got it working...
Any ideas

**Comment by Luzox** [comment]
#bump, same problem...

**Comment by marknx** [comment]
same here, no errors

**Comment by lucasvperini** [comment]
same here...

**Comment by lucasvperini** [comment]
any fixes?

**Comment by Luzox** [comment]
nop still no answer

**Comment by HawaiiBeach** [comment]
Implement it yourself. esx_identity is deprecated
