### ISSUE TITLE
listener.js:87 - cannot read proeprty 'id' of null

### ISSUE THREAD

**Issue by ElPumpo** [ESX-PUBLIC/esx_scoreboard#2]
![image](https://forum.fivem.net/uploads/default/optimized/3X/7/5/757c889db013cbae76ae3976b4392e29813bce60_1_1035x439.jpeg)

**Comment by HawaiiBeach** [comment]
https://github.com/ESX-PUBLIC/esx_scoreboard/blob/a7cb0ed6576fab910db147b82400d68ddd5f3f98/html/listener.js#L85

is to blame. it sometimes only returns `null` and I'm not sure why.

**Comment by HawaiiBeach** [comment]
guessing this was fixed...
