### ISSUE TITLE
no server sided time

### ISSUE THREAD

**Issue by TanguyOrtegat** [ESX-PUBLIC/esx_scoreboard#21]
add these lines in sevrer file:
Citizen.CreateThread(function()
	local uptimeMinute, uptimeHour, uptime = 0, 0, ''

	while true do
		Citizen.Wait(1000 * 60) -- every minute
		uptimeMinute = uptimeMinute + 1

		if uptimeMinute == 60 then
			uptimeMinute = 0
			uptimeHour = uptimeHour + 1
		end

		uptime = string.format("%02dh %02dm", uptimeHour, uptimeMinute)
		SetConvarServerInfo('Uptime', uptime)

		TriggerClientEvent('uptime:tick', -1, uptime)
		TriggerEvent('uptime:tick', uptime)
	end
end)

**Comment by HawaiiBeach** [comment]
Uptime is a seperate resource if people want it. Im not going to merge uptime with this project

**Comment by TanguyOrtegat** [comment]
alright, i taught you forgot :)
