### ISSUE TITLE
Error when opening menu

### ISSUE THREAD

**Issue by Brodys** [ESX-PUBLIC/esx_scoreboard#23]
Menu opens fine, this is what it looks like when i log in:

![image](https://user-images.githubusercontent.com/4230745/59946089-249aa880-942f-11e9-9f1a-07e72c56e049.png)

This is the error i get: 

`Access denied for command add_principal.
Error running system event handling function for resource esx_scoreboard: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @esx_scoreboard/server/main.lua:43: attempt to index a nil value (local 'xPlayer')
stack traceback:
        @esx_scoreboard/server/main.lua:43: in function 'AddPlayerToScoreboard'
        @esx_scoreboard/server/main.lua:17: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
Error running system event handling function for resource esx_datastore: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @esx_datastore/server/main.lua:88: attempt to index a nil value (local 'xPlayer')
stack traceback:
        @esx_datastore/server/main.lua:88: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>`

main/server/line:17:

AddEventHandler('esx:playerLoaded', function(playerId, xPlayer)
	AddPlayerToScoreboard(xPlayer, true) <-------------
end)

main/server/line:43

function AddPlayerToScoreboard(xPlayer, update)
	local playerId = xPlayer.source <-------------

	connectedPlayers[playerId] = {}
	connectedPlayers[playerId].ping = GetPlayerPing(playerId)
	connectedPlayers[playerId].id = playerId
	connectedPlayers[playerId].name = xPlayer.getName()
	connectedPlayers[playerId].job = xPlayer.job.name

I noticed now when im logged in and i stop and start the script it works for the players online, then same thing happens when someone logs in.

![image](https://user-images.githubusercontent.com/4230745/59946185-70e5e880-942f-11e9-9f8d-75d3162e6cbe.png)

Any solutions?

**Comment by Keyinator** [comment]
Should be fixed in my fork: https://github.com/Keyinator/esx_scoreboard
Just download and replace

**Comment by HawaiiBeach** [comment]
update esx
