### ISSUE TITLE
cant load main.lua

### ISSUE THREAD

**Issue by EmpanTTV** [ESX-PUBLIC/esx_scoreboard#30]
Creating script environments for esx_scoreboard
Error loading script server/main.lua in resource esx_scoreboard: @esx_scoreboard/server/main.lua:6: attempt to index a nil value (global 'ESX')
stack traceback:
        @esx_scoreboard/server/main.lua:6: in main chunk
Failed to load script server/main.lua.
Started resource esx_scoreboard

**Comment by HawaiiBeach** [comment]
F
