### ISSUE TITLE
Bug in scoreboard for normal people.

### ISSUE THREAD

**Issue by DennisFusha** [ESX-PUBLIC/esx_scoreboard#33]
Hello,

When u have superadmin the board looks like this:
![image](https://user-images.githubusercontent.com/29520150/77368987-cbfd9080-6d5d-11ea-91b5-a145ba9f0610.png)

But when u don't have admin nor superadmin it looks like this:
![image](https://user-images.githubusercontent.com/29520150/77369017-dae44300-6d5d-11ea-84f1-fa8c58875ed5.png)

As you can see it's just bugged out.
Can someone fix this or send me a fix or tell me how?

**Comment by rex2630** [comment]
Yeah, I have same problem

**Comment by DennisFusha** [comment]
> Yeah, I have same problem

U could maybe look into it I've seen u helping other ESX including this one?
