### ISSUE TITLE
SCRIPT ERROR: @esx_skin/server/main.lua:49: attempt to index a nil value local ('user') #34

### ISSUE THREAD

**Issue by 2ratheflouterman** [ESX-PUBLIC/esx_scoreboard#35]
![merhaba](https://user-images.githubusercontent.com/63187183/78554711-4fb28500-7814-11ea-98ee-72710714e6d7.png)

I have a problem with this error. I can't solve this problem so I need help to solve it. I noticed that It happens due to 'esx_kashacters'. When I try to delete the 'esx_kasharacters', It works clearly.

**Comment by HawaiiBeach** [comment]
open issue one more time = ban

**Comment by 2ratheflouterman** [comment]
Why did you close 2 times? I didn't do anything wrong. You are closing and
you don't say why. I have a problem and I'm asking to the people. I want to
solve it

**Comment by HumanTree92** [comment]
Clearly if the issue is solved by removing esx_kasharacters then the problem is with that script. It's best u contact the person that made that script and have them fix it.
