### ISSUE TITLE
Duplicate player names with zero ping

### ISSUE THREAD

**Issue by mortdudley** [ESX-PUBLIC/esx_scoreboard#37]
We are having an issues with duplicate player names. It seems to happen randomly and I cannot see any errors in either the client or server console. In the attached image, it just doesn't seem to be properly dropping players from the scoreboard when they leave the server. At the time the attached screenshot was taken, there were only 11 players connected to the server.

![image](https://user-images.githubusercontent.com/57285895/78864944-538e1380-7a6f-11ea-9d73-2f5031889d7d.png)

**Comment by HawaiiBeach** [comment]
a problem with your server
