### ISSUE TITLE
I have rp names and want to Show STEAMID on scoreboard

### ISSUE THREAD

**Issue by MaldoNanoche** [ESX-PUBLIC/esx_scoreboard#6]
i just want to have on my scoreaboard SteamID names for Steam(RP names) can someone help me to get it? 
![image](https://user-images.githubusercontent.com/45569776/49696414-da945880-fba9-11e8-834d-3fef06b83e99.png)
just want to show steamid for roleplayname

**Comment by tonnizi** [comment]
connectedPlayers[player].name = result[1].firstname .. ' ' .. result[1].lastname replace --> connectedPlayers[player].name = result[1].name

**Comment by HawaiiBeach** [comment]
https://github.com/ESX-PUBLIC/esx_scoreboard/pull/7

**Comment by MaldoNanoche** [comment]
![image](https://user-images.githubusercontent.com/45569776/49794383-b5cdeb80-fd37-11e8-9f88-6e118056c8b6.png)
want to get id like this on scoreboard ;/

**Comment by Itszipzon** [comment]
How did u manage to get rpnames? the only thing showing to me is the steam names. i want to make the first and last name people create to be shown
